name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: vm-api-pixel
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Pull Docker image from Docker Hub
        run: docker pull pixelapi/spring_app:latest

      - name: Run Docker container
        run: docker run -d -p 8080:8080 --name spring_app_container pixelapi/spring_app:latest
